name: language_detection_diplom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  translate: ^1.0.0
  translator: ^0.1.7
  googleapis: ^11.0.0
  http: ^0.13.5
  google_cloud_translation: ^0.0.3
  google_mlkit_language_id: ^0.6.0
  flutter_tts: ^3.6.3
  google_translator: ^1.0.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  hidden_drawer_menu: ^3.0.1
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  firebase_storage: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
