// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8TUKh1VTOVAtlYILiZbB7HyWHUaRFKs',
    appId: '1:1020078027836:web:4c5bf69274e6378483bf39',
    messagingSenderId: '1020078027836',
    projectId: 'language-recognition-free',
    authDomain: 'language-recognition-free.firebaseapp.com',
    storageBucket: 'language-recognition-free.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DRcPIV823s5k5pKQDs_DTXDcuown3KU',
    appId: '1:1020078027836:android:ce23bf7bd833cafa83bf39',
    messagingSenderId: '1020078027836',
    projectId: 'language-recognition-free',
    storageBucket: 'language-recognition-free.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2pq5IfPcGmN-R91nJIeQuw_qY3DydiM',
    appId: '1:1020078027836:ios:32787832fba13caa83bf39',
    messagingSenderId: '1020078027836',
    projectId: 'language-recognition-free',
    storageBucket: 'language-recognition-free.appspot.com',
    iosClientId: '1020078027836-edhi5vd5d8c95ho136ehe3jrgc1m093s.apps.googleusercontent.com',
    iosBundleId: 'com.example.languageDetectionDiplom',
  );
}
